plugins {
    id 'fabric-loom'
    id 'maven-publish'
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

base {
    archivesName = "${mod_id}-fabric"
}

repositories {
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft_version}:${parchment_mappings_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    implementation project(":common")
    
    implementation "me.zeroeightsix:fiber:0.23.0-2"
    include "me.zeroeightsix:fiber:0.23.0-2"
}

loom {
    def aw = file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath = aw
    }

    runs {
        client {
            client()
            generateRunConfig = true
            runDirectory = 'runs/client'
        }
        server {
            server()
            generateRunConfig = true
            runDirectory = 'runs/server'
        }
    }
    
    runConfigs.configureEach {
        property('mixin.debug.countInjections', 'true')
    }
    
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(":common").sourceSets.main
            
            //workaround to add the correct Eclipse output folder from :common to the fabric.classPathGroups property,
            //to make sure the assets and data from :common are loaded properly when launching in Eclipse
            getModFiles().from(project(":common").file("bin/main"))
        }
    }
    
    mixin.useLegacyMixinAp = false
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(project(":common").sourceSets.main.allSource)
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    dependsOn(project(":common").sourceSets.main.resources)
    from(project(":common").sourceSets.main.resources)
    exclude "META-INF/accesstransformer.cfg"
    
    var replaceProperties = [
            java_version           : java_version,
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            fabric_version         : fabric_version,
            fabric_loader_version  : fabric_loader_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(project(":common").sourceSets.main.allJava)
    source(project(":common").sourceSets.main.allJava)
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = project.java_version as Integer
}

java.toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)

task publishCurseForge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = findProperty('curseForgeApiKey')
    def mainFile = upload(227449, remapJar)
    mainFile.addModLoader('Fabric')
    mainFile.addRequirement('fabric-api')
    mainFile.releaseType = mod_release_type
    mainFile.changelog = file('../changelog.md')
    mainFile.changelogType = 'markdown'
}

modrinth {
    token = findProperty('modrinthApiToken')
    projectId = 'tntutils'
    versionType = mod_release_type
    uploadFile = remapJar
    gameVersions = [minecraft_version]
    loaders = ['fabric']
    dependencies {
        required.project 'fabric-api'
    }
    changelog = file('../changelog.md').text
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }

    repositories {

    }
}
