plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge'
    id 'net.darkhax.curseforgegradle'
    id 'com.modrinth.minotaur'
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = "${mod_id}-forge"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)

legacyForge {
    version = "${project.minecraft_version}-${project.forge_version}"

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    validateAccessTransformers = true

    runs {
        client {
            client()
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty 'mixin.debug.countInjections', 'true'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
            sourceSet(project(":common").sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation project(":common")
}

tasks.named('compileJava', JavaCompile) {
    dependsOn(project(":common").sourceSets.main.allSource)
    source(project(":common").sourceSets.main.allSource)
}

processResources {
    dependsOn(project(":common").sourceSets.main.resources)
    from(project(":common").sourceSets.main.resources)
}

tasks.named('javadoc', Javadoc).configure {
    dependsOn(project(":common").sourceSets.main.allJava)
    source(project(":common").sourceSets.main.allJava)
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version           : minecraft_version,
            minecraft_version_range     : minecraft_version_range,
            forge_version               : forge_version,
            forge_version_range         : forge_version_range,
            forge_loader_version_range  : forge_loader_version_range,
            mod_id                      : mod_id,
            mod_name                    : mod_name,
            mod_license                 : mod_license,
            mod_version                 : version,
            mod_authors                 : mod_authors,
            mod_description             : mod_description
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
// Include the output of "generateModMetadata" as an input directory for the build
// this works with both building through Gradle and the IDE.
sourceSets.main.resources.srcDir generateModMetadata
// To avoid having to run "generateModMetadata" manually, make it run on every project reload
legacyForge.ideSyncTask generateModMetadata

task publishCurseForge(type: net.darkhax.curseforgegradle.TaskPublishCurseForge) {
    apiToken = findProperty('curseForgeApiKey')
    def mainFile = upload(227449, jar)
    mainFile.addModLoader('Forge')
    mainFile.releaseType = mod_release_type
    mainFile.changelog = file('../changelog.md')
    mainFile.changelogType = 'markdown'
}

modrinth {
    token = findProperty('modrinthApiToken')
    projectId = 'tntutils'
    versionType = mod_release_type
    uploadFile = jar
    gameVersions = [minecraft_version]
    loaders = ['forge']
    changelog = file('../changelog.md').text
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url = "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
