plugins {
    id 'java-library'
    id 'net.neoforged.moddev.legacyforge'
}

repositories {
    mavenLocal()
}

java.toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)

legacyForge {
    mcpVersion = project.minecraft_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    //FIXME: Access transformers don't seem to work with LegacyForge vanilla mode
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    validateAccessTransformers = true
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: project.mixin_version
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

pluginManager.withPlugin('eclipse') {
    eclipse.project.name = "common-${project.minecraft_version}"
}
